name: automerge
on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          MERGE_LABELS: "dependencies"
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"